name: assignment-test
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment5-buildroot
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build aesdsocket
        run: |
          make clean
          make  # hoặc lệnh bạn dùng để build binary aesdsocket cho x86

      - name: Start aesdsocket daemon
        run: |
          rm -f /var/tmp/aesdsocketdata.txt
          ./aesdsocket -d
          sleep 1

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: |
          ssh-add -D
